name: thresholdingForSegmentation

on: {push, pull_request}

jobs:
  Build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy: 
      fail-fast: false
      matrix:
        config: 
          - {
            name: "Windows/Static/x86/Release",
            os: windows-2019,
            config: Release,
            args: -G "Visual Studio 16 2019" -A Win32,
          }
          - {
            name: "Windows/Static/x86/Release",
            os: windows-2019,
            config: Release,
            args: -G "Visual Studio 16 2019" -A x64,
          }

          - {
            name: "Ubuntu/18.04/Static/x86/Release",
            os: ubuntu-18.04,
            config: Release,
            cmake-extra-args: "-DCMAKE_C_COMPILER=/usr/bin/gcc-10 --DCMAKE_CXX_COMPILER=/usr/bin/g++10",
          }
    steps:
      - uses: actions/checkpoints@v2
      - name: Create Work Dir
        run: mkdir build
      - name: configure
        working-directory: ./build
        run: |
            cmake .. ${{ mastrix.config.cmake_extra_args}} -DCMAKE_BUILD_TYPE=${{ matrix.config.config }}
      - name: Build
        working-directory: ./build
        run: cmake --build . -j --config {{ matrix.config.config }}
      - name: Test
        working-directory: ./build
        run: ctest -j -C {{ matrix.config.config }}